const LOGIN = 'LOGIN';
const LOGIN_TRUE = 'true';
const LOGIN_FALSE = 'false';
const DEFAULT_REQUEST = 'DEFAULT_REQUEST';
const DATE_DEFAULT = 'DATE_DEFAULT';
const REQUEST = 'REQUEST';
const WEATHER_PROPS = 'WEATHER_PROPS';
const LOADER_ON = 'LOADER_ON';
const WEATHER_DATA = 'WEATHER_DATA';
const LOADER_OFF = 'LOADER_OFF';
const QUIT = 'QUIT';
const FAVORITE = 'FAVORITE';

export {
  LOGIN,
  LOGIN_TRUE,
  LOGIN_FALSE,
  DEFAULT_REQUEST,
  DATE_DEFAULT,
  REQUEST,
  WEATHER_PROPS,
  LOADER_ON,
  WEATHER_DATA,
  LOADER_OFF,
  QUIT,
  FAVORITE,
};
