const LOGIN = 'LOGIN';
const LOGIN_TRUE = 'true';
const LOGIN_FALSE = 'false';
const WEATHER_REQUEST = 'WEATHER_REQUEST';
const CURRENCY_REQUEST = 'CURRENCY_REQUEST';
const WEATHER_PROPS = 'WEATHER_PROPS';
const CURRENCY_PROPS = 'CURRENCY_PROPS';
const LOADER_ON = 'LOADER_ON';
const LOADER_OFF = 'LOADER_OFF';
const WEATHER_DATA = 'WEATHER_DATA';
const QUIT = 'QUIT';
const RATE = 'RATE';
const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
const GUEST_ENTER = 'GUEST_ENTER';
const SWITCH_COUNTRY = 'SWITCH_COUNTRY';

export {
  LOGIN,
  LOGIN_TRUE,
  LOGIN_FALSE,
  WEATHER_REQUEST,
  CURRENCY_REQUEST,
  WEATHER_PROPS,
  CURRENCY_PROPS,
  LOADER_ON,
  LOADER_OFF,
  WEATHER_DATA,
  QUIT,
  RATE,
  REGISTRATION_SUCCESS,
  SWITCH_LANGUAGE,
  GUEST_ENTER,
  SWITCH_COUNTRY,
};
