const LOGIN = 'LOGIN';
const LOGIN_TRUE = 'true';
const LOGIN_FALSE = 'false';
const DEFAULT_REQUEST = 'DEFAULT_REQUEST';
const DATE_DEFAULT = 'DATE_DEFAULT';
const REQUEST = 'REQUEST';
const DATE_PICKER = 'DATE_PICKER';
const LOADER_ON = 'LOADER_ON';
const RESPONSE = 'RESPONSE';
const LOADER_OFF = 'LOADER_OFF';
const QUIT = 'QUIT';
const FAVORITE = 'FAVORITE';

export {
  LOGIN,
  LOGIN_TRUE,
  LOGIN_FALSE,
  DEFAULT_REQUEST,
  DATE_DEFAULT,
  REQUEST,
  DATE_PICKER,
  LOADER_ON,
  RESPONSE,
  LOADER_OFF,
  QUIT,
  FAVORITE,
};
